# Generated by Django 3.2.16 on 2023-01-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque atual'),
        ),
    ]
